create database Employeemanagement;
use Employeemanagement;
create table employee(employee_id int primary key,emp_name varchar(30),gender varchar(30),department varchar(30),salary int ,phone int);
use Employeemanagement;
create table empleave(id int,emp_id int,leave_type varchar(30),startdate date,enddate date);
use Employeemanagement;
create table attendance(id int primary key,employee_id int,attendancde varchar(20),att_date date, FOREIGN KEY(employee_id) REFERENCES employee(employee_id));
insert into employee values(1,"john","male","HR",250000,987654321),(2,"mathew","male","finance",60000,985234321),(3,"MINU","female","IT",45000,987665321);
insert into empleave values(201,1,"sick leave",'2025-06-01','2025-06-03'),(202,2,"casual leave",'2025-06-03','2025-06-06'),(203,3,"Annual leave",'2025-06-09','2025-06-12');
select * from employee;
UPDATE employee SET salary = 65000 WHERE employee_id= 2;
SET SQL_SAFE_UPDATES = 0;
delete from employee where employee_id=1;
select emp_name from employee;
select emp_name,department from employee;
select * from employee where department="IT";
select * from employee where salary >40000;
select COUNT(*) AS total_employees from employee;
select * from employee order by salary ASC;
select * from employee order by salary DESC;
select max(salary) as highest_salary from employee;
select min(salary) as lowest_salary from employee;
select avg(salary) as average_salary from employee;
select * from employee where emp_name LIKE "% A";
